In [113]:
#https://machinelearningmastery.com/index-slice-reshape-numpy-arrays-machine-learning-python/

import numpy as np

In [114]:
# takes a list / converts to np array / prints np array / prints data type 

def np_array_gen(lst):
    data = array(lst)
    print(data)
    print(type(data))
    return data
    
    
data = [1,2,3,4]

data_two = [[11,22],
            [33,44],
            [55,66]]

data = np_array_gen(data)
print('-' *30)
data_two = np_array_gen(data_two)
    
    

[1 2 3 4]
<class 'numpy.ndarray'>
------------------------------
[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>


In [115]:
data_three = array([11,22,33,44,55])

In [116]:
#value and index print loop
for index,value in enumerate(data_three):
    print(index,value)
    

0 11
1 22
2 33
3 44
4 55


In [117]:
# while loop to count 

In [118]:
# while loop to count and print backwards and forwards
itz = len(data_three) - 1
itz2 = 0
print('Backwards list print')
while itz > -1:
    print(data_three[itz])
    itz -= 1
else:
    print('Forwards list print')
    while itz2 < 5:
        print(data_three[itz2])
        itz2 += 1

Backwards list print
55
44
33
22
11
Forwards list print
11
22
33
44
55


In [119]:
#Calling values by their positive and negtative index

for i,v in enumerate(data_three):
    print("Value: ", v, "Positive index: ",i ,"negative index: ", i - len(data_three))
    
print("Forwards",data_three[0:])
print("Backwards",data_three[::-1])

    

Value:  11 Positive index:  0 negative index:  -5
Value:  22 Positive index:  1 negative index:  -4
Value:  33 Positive index:  2 negative index:  -3
Value:  44 Positive index:  3 negative index:  -2
Value:  55 Positive index:  4 negative index:  -1
Forwards [11 22 33 44 55]
Backwards [55 44 33 22 11]


In [120]:
#2dimensional indexing
print(data_two[0])
print(data_two[0,0])
print(data_two[0,1])
print(data_two[0,0],data_two[0,1])

for i in data_two:
    print(i)
    print(i[0],i[1])

[11 22]
11
22
11 22
[11 22]
11 22
[33 44]
33 44
[55 66]
55 66


In [121]:
#One dimensional slicing

#all elements
print(data)
print(data[:])
#1st item
print(data[0:1])
#last item
print(data[-1:])


[1 2 3 4]
[1 2 3 4]
[1]
[4]


In [122]:
#2d slicing

In [123]:
print(data_two)
#added value 5 onto the end of each Y list
data_two = np.insert(data_two,2, 5, axis=1)
print()
print(data_two)

[[11 22]
 [33 44]
 [55 66]]

[[11 22  5]
 [33 44  5]
 [55 66  5]]


In [136]:
X,y = data_two[:,:-1], data_two[:,-1]
print("X",X)
print('y',y)

X [[11 22]
 [33 44]
 [55 66]]
y [5 5 5]


In [151]:
#Splitting train and test rows
train = data_two[:split, :]
train

array([[11, 22,  5],
       [33, 44,  5]])

In [152]:
data_two

array([[11, 22,  5],
       [33, 44,  5],
       [55, 66,  5]])

In [159]:
test = data_two[split:]
test

array([[55, 66,  5]])